#!/bin/bash
start_script() {
    if ps aux | grep "[w]arsigs-bootstrap" > /dev/null
    then
        : #noop
    else
        echo -e "\033[0;33mAttempting to start Warface-Signatures Bootstrap...\033[0m"

        # start our node server
        cd ~/warface-signature-maker/app/Files
        node node/warsigs-bootstrap.js 2>&1 >> /var/log/warsigs.log &
    fi

    echo -e "\033[0;32mWarface-Signatures is now running.\033[0m\n"
}

stop_script() {
    echo -e "\033[0;33mStopping Warface-Signatures Bootstrap..."

    kill $(ps aux | grep "[w]arsigs-bootstrap" | awk '{print $2}') > /dev/null

    echo -e "\033[0;31mWarface-Signatures is now stopped.\033[0m\n"
}

status_script() {
    pid=$(ps aux | grep "[w]arsigs-bootstrap" | awk '{print $2}')

    if [ -z "$pid" ]; #check if empty
    then
        echo -e "\033[0;32mWarface-Signatures is not running.\033[0m\n"
    else
        echo -e "\033[0;32mWarface-Signatures is running with pid $pid.\033[0m\n"
    fi
}

case "$1" in
    start)   start_script ;;
    stop)    stop_script ;;
    restart) stop_script; start_script ;;
    status) status_script ;;
    *) echo "usage: $0 start|stop|restart|status" >&2
       exit 1
       ;;
esac
